import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

import { DIMENSIONS, METRICS, METRIC_IDS, observationOf } from "../../lib/metrics.mjs";
import { scoreRun as scoreRunUnbounded } from "../../lib/scorer-v1.mjs";

// #556: `scoreRun` and `issuanceCheck` withhold issuance unless the confinement gate says the run
// was official, and absent evidence withholds like a negative verdict. These tests are about the
// arithmetic and the metric gates, so the boundary is stated once here rather than at every call:
// what they assert is what the scorer does with observations, not what this machine's isolation
// backend can do.
const UNDER_AN_OFFICIAL_BOUNDARY = { officialIssuance: { official: true, reasons: [] } };
const scoreRun = (observations, context = {}) => scoreRunUnbounded(observations, { ...UNDER_AN_OFFICIAL_BOUNDARY, ...context });


// The pack is hand-computed from the declared weights. A pack generated by the scorer agrees with
// it by construction and checks nothing, which is the shape of every vacuous fixture gate.
const pack = JSON.parse(readFileSync(new URL("../../fixtures/scoring/vectors.v1.json", import.meta.url), "utf8"));

// An unobserved metric is present and NOT_OBSERVED, never absent. Omitting it is a different
// thing -- a result that does not mention a metric is malformed, not a result that did not observe
// one -- and the contract reports the difference.
const observationsFor = (vector) =>
  METRIC_IDS.map((id) => {
    if ((vector.unobserved ?? []).includes(id)) return observationOf({ metric_id: id, reason: "not observed" });
    const failing = vector.failing_subcheck?.[id];
    const passing = vector.passing[id] ?? vector.passing.default;
    return observationOf({
      metric_id: id,
      verifier_id: "vector.v1",
      subchecks: METRICS[id].subchecks.map((subcheck, index) => ({
        id: subcheck,
        pass: failing === subcheck ? false : index < passing
      })),
      evidence_ids: ["vector"],
      reason: vector.vector_id
    });
  });

test("the pack declares the same weights the contract does", () => {
  // Two places holding the scale is how a fixture starts testing yesterday's arithmetic.
  for (const [dimension, weight] of Object.entries(pack.weights)) {
    assert.equal(DIMENSIONS[dimension].weight, weight, dimension);
  }
  assert.equal(pack.contract_id, "aos-metric-contract.v1");
  assert.equal(pack.scorer_id, "aos-mvp-scorer.v1");
});

for (const vector of pack.vectors) {
  test(`vector ${vector.vector_id}`, () => {
    const scored = scoreRun(observationsFor(vector), { safetyState: "S0" });
    const expect = vector.expect;

    assert.equal(scored.status, expect.status, vector.note);
    assert.equal(scored.issued, expect.issued, vector.note);
    assert.equal(scored.coverage.observed, expect.observed, "observed count");

    if (expect.score === null) {
      assert.equal(scored.score, null, "a withheld score must not be present");
      assert.equal(scored.provisional_raw, expect.provisional_raw, "provisional");
    } else {
      assert.equal(scored.score.raw, expect.raw, "raw");
      assert.equal(scored.score.final, expect.final, "final");
      assert.equal(scored.score.band, expect.band, "band");
    }
    if (Object.hasOwn(expect, "unobserved_weight")) {
      assert.equal(scored.unobserved_weight, expect.unobserved_weight, "unobserved weight");
    }
  });
}

test("the pack covers a withheld score, a capped one and a clean one", () => {
  // A pack of nothing but passing runs would let every gate and every ceiling rot unnoticed.
  const statuses = new Set(pack.vectors.map((vector) => vector.expect.status));
  assert.equal(statuses.has("SCORED"), true);
  assert.equal(statuses.has("INCOMPLETE"), true);
  assert.equal(statuses.has("UNSAFE"), true);
  assert.equal(pack.vectors.some((vector) => vector.expect.final < vector.expect.raw), true, "no capped vector");
});

test("every vector carries the arithmetic it expects", () => {
  // The note is what makes the pack checkable by a person rather than only by this file.
  for (const vector of pack.vectors) {
    assert.equal(typeof vector.note, "string", vector.vector_id);
    assert.equal(vector.note.length > 30, true, vector.vector_id);
  }
});
