import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, lstatSync, readdirSync, readFileSync } from "node:fs";
import { dirname, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import test from "node:test";

const repositoryRoot = resolve(fileURLToPath(new URL("../..", import.meta.url)));

const README_PATH = "README.md";
const CONTRIBUTING_PATH = "CONTRIBUTING.md";
const VALIDATION_PATH = "docs/VALIDATION.md";
const LIMITATIONS_PATH = "docs/LIMITATIONS.md";
const INTENDED_USE_PATH = "docs/INTENDED_USE.md";
const EXAMPLES_README_PATH = "examples/README.md";
const ADAPTER_TEMPLATE_PATH = ".github/ISSUE_TEMPLATE/adapter.yml";
const SCENARIO_TEMPLATE_PATH = ".github/ISSUE_TEMPLATE/scenario.yml";

const DEMO_COMMAND = "node scripts/schema-conformance.mjs";
const SCORER_COMMAND = "node --test packages/scorer/test/score.test.ts";
const FIXTURE_PACK = "fixtures/scoring/vectors.json";

const REQUIRED_PUBLIC_DOCUMENTS = [
  README_PATH,
  CONTRIBUTING_PATH,
  VALIDATION_PATH,
  LIMITATIONS_PATH,
  INTENDED_USE_PATH,
  EXAMPLES_README_PATH,
  ADAPTER_TEMPLATE_PATH,
  SCENARIO_TEMPLATE_PATH
];

const README_REQUIRED_LINKS = [
  VALIDATION_PATH,
  LIMITATIONS_PATH,
  INTENDED_USE_PATH,
  CONTRIBUTING_PATH,
  EXAMPLES_README_PATH,
  "LICENSE"
];

const PROVISIONAL_LIMIT = "AOS-Coding P0 is EXPERIMENTAL / PROVISIONAL.";
const NO_PERCENTILE_LIMIT = "AOS does not report a percentile.";
const NO_CERTIFICATION_LIMIT = "AOS is not a certification.";
const NO_RANK_LIMIT = "AOS is not a hiring signal, a global rank, or an industry standard.";
const NO_HIRING_USE = "AOS is not a hiring, promotion, or surveillance instrument.";
const NO_SECRET_STORAGE = "Secret values are never stored.";
const TELEMETRY_OFF = "Default telemetry is OFF.";
const PROVENANCE =
  "A score is produced by the deterministic scorer from an aos-trace under a declared Opportunity Profile.";
const NO_HIDDEN_REASONING = "Hidden chain-of-thought is never stored.";
const NO_HIDDEN_ANSWERS =
  "Hidden task answers and gold solutions are not published on the public surface.";
const NO_GENERATED_ATTRIBUTION =
  "Do not add generated attribution or internal agent, model, session, or routing metadata to public GitHub surfaces.";
const CONTRIBUTION_STILL_BLOCKED =
  "Contribution acceptance and redistribution remain blocked until the E14/G4 LICENSE and publication gate clears.";
const G4_NOT_CLEARED = "G4 publication is not cleared.";
const NOT_CALIBRATION = "This document is not a human-calibration result.";
const DEMO_IS_NOT_AN_ASSESSMENT =
  "This demo does not run an assessment and is not the aos CLI.";
const NO_PUBLIC_PACKAGE = "No public package has been approved.";
const ADAPTER_ROUTE_TEXT =
  "These routes document where an adapter or scenario would land. They do not accept external contributions while contributor terms are unresolved.";

const STALE_LICENSE_CLAIMS = [
  "No OSS license has been selected",
  "No OSS license or public package has been approved"
];

const FORBIDDEN_AFFIRMATIVE_CLAIMS = [
  "industry standard assessment",
  "official certification",
  "hiring-ready score",
  "environment-independent personal ability",
  "validated percentile",
  "calibrated personal score"
];

const SECRET_PATTERNS = [
  { id: "openai-key", pattern: /\bsk-[A-Za-z0-9]{20,}\b/ },
  { id: "github-token", pattern: /\bghp_[A-Za-z0-9]{20,}\b/ },
  { id: "private-key", pattern: /-----BEGIN (?:RSA |OPENSSH |EC )?PRIVATE KEY-----/ },
  { id: "aws-key", pattern: /\bAKIA[0-9A-Z]{16}\b/ },
  { id: "slack-token", pattern: /\bxox[baprs]-[A-Za-z0-9-]{10,}\b/ }
];

const ATTRIBUTION_PATTERNS = [
  { id: "generated-by", pattern: /generated by (?:chatgpt|claude|copilot|gpt-|gemini|grok)/i },
  { id: "co-authored", pattern: /co-authored-by:\s*(?:copilot|chatgpt|claude|cursor)/i },
  { id: "session-meta", pattern: /\b(?:model_session_id|agent_session_id|X-Agent-Session)\b/ }
];

const HIDDEN_ANSWER_PATTERNS = [
  { id: "hidden-answer-heading", pattern: /^#{1,6}\s+hidden (?:task )?answer\b/im },
  { id: "gold-solution-heading", pattern: /^#{1,6}\s+gold solution\b/im },
  { id: "task-answer-heading", pattern: /^#{1,6}\s+task answer\b/im }
];

const asRepositoryRelative = (absolutePath) =>
  relative(repositoryRoot, absolutePath).replaceAll("\\", "/");

const readPublicFile = (relativePath) => {
  const absolute = resolve(repositoryRoot, relativePath);
  let entry;
  try {
    entry = lstatSync(absolute);
  } catch {
    assert.fail(`E14-002 public document is absent: ${relativePath}`);
  }
  if (entry.isSymbolicLink() || !entry.isFile()) {
    assert.fail(`E14-002 public document is not a regular file: ${relativePath}`);
  }
  const text = readFileSync(absolute, "utf8").replaceAll("\r\n", "\n");
  assert.ok(text.trim().length > 0, `E14-002 public document is empty: ${relativePath}`);
  return text;
};

const walkRegularFiles = (relativeDirectory) => {
  const absoluteDirectory = resolve(repositoryRoot, relativeDirectory);
  if (!existsSync(absoluteDirectory)) return [];
  const found = [];
  const visit = (absolute) => {
    let entry;
    try {
      entry = lstatSync(absolute);
    } catch {
      return;
    }
    if (entry.isSymbolicLink()) return;
    if (entry.isFile()) {
      found.push(asRepositoryRelative(absolute));
      return;
    }
    if (!entry.isDirectory()) return;
    for (const name of readdirSync(absolute).sort()) {
      visit(resolve(absolute, name));
    }
  };
  visit(absoluteDirectory);
  return found;
};

const ownedSurfacePaths = () => {
  const walked = [
    ...walkRegularFiles("examples"),
    ...walkRegularFiles("conformance"),
    ...walkRegularFiles(".github")
  ];
  return [...new Set([...REQUIRED_PUBLIC_DOCUMENTS, ...walked])].sort();
};

const loadOwnedSurface = () =>
  ownedSurfacePaths().map((path) => ({ path, text: readPublicFile(path) }));

const stripFencedBlocks = (text) => text.replaceAll(/```[\s\S]*?```/g, "");

const extractFencedCommandLines = (text) =>
  [...text.matchAll(/```(?:bash|sh)?\n([\s\S]*?)```/g)]
    .flatMap(([, body]) => body.split("\n"))
    .map((line) => line.replace(/^\s*\$\s*/, "").trim())
    .filter((line) => line.length > 0 && !line.startsWith("#"));

const extractMarkdownHrefs = (text) =>
  [...stripFencedBlocks(text).matchAll(/!?\[(?:[^\]]*)\]\(([^)\s]+)(?:\s+"[^"]*")?\)/g)]
    .map(([, href]) => href);

const resolveLocalHref = (fromPath, href) => {
  const bare = href.split("#")[0];
  if (bare === "") return null;
  if (/^[a-z][a-z0-9+.-]*:/i.test(bare)) return null;
  const fromDirectory = dirname(resolve(repositoryRoot, fromPath));
  const target = resolve(fromDirectory, decodeURIComponent(bare));
  const relation = relative(repositoryRoot, target);
  if (relation === "" || relation === ".." || relation.startsWith(`..${sep}`) || relation.startsWith("/")) {
    return null;
  }
  return asRepositoryRelative(target);
};

const findPatternHits = (surface, patterns) => {
  const hits = [];
  for (const { path, text } of surface) {
    for (const { id, pattern } of patterns) {
      pattern.lastIndex = 0;
      if (pattern.test(text)) hits.push(`${path} (${id})`);
    }
  }
  return hits;
};

const findPhraseHits = (surface, phrases) => {
  const hits = [];
  for (const { path, text } of surface) {
    for (const phrase of phrases) {
      if (text.includes(phrase)) hits.push(`${path}: ${phrase}`);
    }
  }
  return hits;
};

const assertDocumentedCommand = (texts, command, label) => {
  const lines = texts.flatMap(extractFencedCommandLines);
  assert.ok(
    lines.includes(command),
    `public surface omits the ${label} command`
  );
};

const assertContains = (text, snippet, message) => {
  assert.ok(text.includes(snippet), message);
};

test("commands", () => {
  const readme = readPublicFile(README_PATH);
  const examples = readPublicFile(EXAMPLES_README_PATH);
  const validation = readPublicFile(VALIDATION_PATH);
  const texts = [readme, examples, validation];

  assertContains(examples, DEMO_IS_NOT_AN_ASSESSMENT, "examples/README.md does not bound the demo");
  assertDocumentedCommand(texts, DEMO_COMMAND, "one-command schema/fixture demo");
  assertDocumentedCommand(texts, SCORER_COMMAND, "scorer verification");
  assert.ok(
    texts.some((text) => text.includes(FIXTURE_PACK)),
    "public surface omits fixture verification"
  );
  assert.ok(
    existsSync(resolve(repositoryRoot, "scripts/schema-conformance.mjs")),
    "documented demo command is not a real repository command"
  );
  assert.ok(
    existsSync(resolve(repositoryRoot, FIXTURE_PACK)),
    "documented fixture pack is not a real repository path"
  );

  const env = { ...process.env };
  delete env.NODE_TEST_CONTEXT;
  delete env.NODE_OPTIONS;
  const demo = execFileSync(process.execPath, ["scripts/schema-conformance.mjs"], {
    cwd: repositoryRoot,
    encoding: "utf8",
    env
  });
  assert.match(
    demo,
    /^SCHEMA_CONFORMANCE_PASS /m,
    "one-command demo did not verify schema and fixtures"
  );
});

test("links", () => {
  const readme = readPublicFile(README_PATH);
  const contributing = readPublicFile(CONTRIBUTING_PATH);
  readPublicFile(VALIDATION_PATH);
  readPublicFile(LIMITATIONS_PATH);
  readPublicFile(INTENDED_USE_PATH);
  readPublicFile(EXAMPLES_README_PATH);
  readPublicFile(ADAPTER_TEMPLATE_PATH);
  readPublicFile(SCENARIO_TEMPLATE_PATH);

  for (const target of README_REQUIRED_LINKS) {
    assert.ok(
      extractMarkdownHrefs(readme).some((href) => href === target || href.endsWith(target)),
      `README.md does not link to ${target}`
    );
  }

  const contributingHrefs = extractMarkdownHrefs(contributing);
  assert.ok(
    contributingHrefs.some((href) => href === "adapters/" || href.startsWith("adapters/")),
    "CONTRIBUTING.md omits an adapter contribution route"
  );
  assert.ok(
    contributingHrefs.some(
      (href) => href === "suites/coding-core-v0/" || href.startsWith("suites/coding-core-v0/")
    ),
    "CONTRIBUTING.md omits a scenario contribution route"
  );
  assert.ok(
    contributingHrefs.some((href) => href.includes("ISSUE_TEMPLATE/adapter.yml")),
    "CONTRIBUTING.md does not link the adapter issue template"
  );
  assert.ok(
    contributingHrefs.some((href) => href.includes("ISSUE_TEMPLATE/scenario.yml")),
    "CONTRIBUTING.md does not link the scenario issue template"
  );
  assertContains(
    contributing,
    ADAPTER_ROUTE_TEXT,
    "CONTRIBUTING.md presents contribution routes as an acceptance path"
  );
  assertContains(
    contributing,
    CONTRIBUTION_STILL_BLOCKED,
    "CONTRIBUTING.md no longer refuses contribution acceptance while contributor terms are unresolved"
  );

  const surface = loadOwnedSurface();
  const broken = [];
  for (const { path, text } of surface) {
    for (const href of extractMarkdownHrefs(text)) {
      const target = resolveLocalHref(path, href);
      if (target === null) continue;
      if (!existsSync(resolve(repositoryRoot, target))) {
        broken.push(`${path} -> ${href}`);
      }
    }
  }
  assert.deepEqual(broken, [], `public surface link is broken: ${broken[0]}`);
});

test("no-claims", () => {
  const limitations = readPublicFile(LIMITATIONS_PATH);
  const intended = readPublicFile(INTENDED_USE_PATH);
  const validation = readPublicFile(VALIDATION_PATH);
  const readme = readPublicFile(README_PATH);
  const contributing = readPublicFile(CONTRIBUTING_PATH);

  assertContains(limitations, PROVISIONAL_LIMIT, "LIMITATIONS.md does not make the provisional limit unavoidable");
  assertContains(limitations, NO_PERCENTILE_LIMIT, "LIMITATIONS.md does not make the no-percentile limit unavoidable");
  assertContains(
    limitations,
    NO_CERTIFICATION_LIMIT,
    "LIMITATIONS.md does not make the no-certification limit unavoidable"
  );
  assertContains(limitations, NO_RANK_LIMIT, "LIMITATIONS.md does not refuse rank and industry-standard claims");
  assertContains(intended, NO_HIRING_USE, "INTENDED_USE.md does not refuse hiring use");
  assertContains(validation, G4_NOT_CLEARED, "VALIDATION.md claims or omits the G4 block");
  assertContains(validation, NOT_CALIBRATION, "VALIDATION.md does not refuse a calibration claim");
  assertContains(readme, NO_PUBLIC_PACKAGE, "README.md no longer states that no public package has been approved");

  const surface = [
    { path: README_PATH, text: readme },
    { path: CONTRIBUTING_PATH, text: contributing },
    { path: VALIDATION_PATH, text: validation },
    { path: LIMITATIONS_PATH, text: limitations },
    { path: INTENDED_USE_PATH, text: intended }
  ];
  const stale = findPhraseHits(surface, STALE_LICENSE_CLAIMS);
  assert.deepEqual(stale, [], `public surface repeats a stale license claim in ${stale[0]}`);
  const forbidden = findPhraseHits(surface, FORBIDDEN_AFFIRMATIVE_CLAIMS);
  assert.deepEqual(forbidden, [], `public surface asserts a forbidden claim: ${forbidden[0]}`);
});

test("no-secrets", () => {
  const intended = readPublicFile(INTENDED_USE_PATH);
  assertContains(intended, NO_SECRET_STORAGE, "INTENDED_USE.md does not refuse secret storage");

  const surface = loadOwnedSurface();
  assert.ok(surface.length > 0, "owned public surface is empty");
  const hits = findPatternHits(surface, SECRET_PATTERNS);
  assert.deepEqual(hits, [], `public surface contains a secret-like value in ${hits[0]}`);
});

test("no-answers", () => {
  const examples = readPublicFile(EXAMPLES_README_PATH);
  const contributing = readPublicFile(CONTRIBUTING_PATH);
  assertContains(examples, NO_HIDDEN_ANSWERS, "examples/README.md does not refuse publication of hidden task answers");
  assertContains(
    contributing,
    NO_HIDDEN_ANSWERS,
    "CONTRIBUTING.md does not refuse publication of hidden task answers"
  );

  const surface = loadOwnedSurface();
  assert.ok(surface.length > 0, "owned public surface is empty");
  const hits = findPatternHits(surface, HIDDEN_ANSWER_PATTERNS);
  assert.deepEqual(hits, [], `public surface publishes a hidden task answer in ${hits[0]}`);
  const forbiddenNames = ownedSurfacePaths().filter((path) =>
    /(?:^|\/)(?:answer|solution|gold)(?:\.[^/]+)?$/i.test(path)
  );
  assert.deepEqual(
    forbiddenNames,
    [],
    `public surface publishes a hidden-answer file: ${forbiddenNames[0]}`
  );
});

test("no-attribution", () => {
  const contributing = readPublicFile(CONTRIBUTING_PATH);
  assertContains(
    contributing,
    NO_GENERATED_ATTRIBUTION,
    "CONTRIBUTING.md does not refuse generated attribution"
  );

  const surface = loadOwnedSurface();
  assert.ok(surface.length > 0, "owned public surface is empty");
  const hits = findPatternHits(surface, ATTRIBUTION_PATTERNS);
  assert.deepEqual(hits, [], `public surface contains generated attribution in ${hits[0]}`);
});

test("telemetry-off", () => {
  const readme = readPublicFile(README_PATH);
  const intended = readPublicFile(INTENDED_USE_PATH);
  const limitations = readPublicFile(LIMITATIONS_PATH);

  assertContains(readme, TELEMETRY_OFF, "README.md omits a zero-telemetry statement");
  assertContains(intended, TELEMETRY_OFF, "INTENDED_USE.md does not state that default telemetry is OFF");
  assertContains(intended, PROVENANCE, "INTENDED_USE.md omits a provenance statement");
  assertContains(intended, NO_HIDDEN_REASONING, "INTENDED_USE.md does not refuse hidden-reasoning capture");
  assertContains(limitations, PROVENANCE, "LIMITATIONS.md omits a provenance statement");
});
